name: workflow-socials

on:
 push:
  branches: [main]

jobs:
    build: 
        runs-on: ubuntu-latest
        strategy:
            matrix: 
                node-version: [22.x]

        steps: 
            - name: clone repo
              uses: actions/checkout@v4

            - name: install node 
              uses: actions/setup-node@v4
              with: 
                node-version: ${matrix.node-version}

            - name: installing npm 
              run: npm install

            - name: starting to test
              run: npm run test 
            
            - name: starting to build
              run: npm run build 
            
            